#----------------------------------------------------------------------
# This file was generated by img2py.py
'''
C:\Python27\Lib\site-packages\wx-2.8-msw-unicode\wx\tools>
C:\Python27\python.exe img2py.py -i path/to/your/icon.ico myIcon.py
import tip_icon
self.ico = tip_icon.gettipimg2Icon()
self.SetIcon(self.ico)
'''
#
from wx.lib.embeddedimage import PyEmbeddedImage

tipimg2 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABHNCSVQICAgIfAhkiAAAB5VJ"
    "REFUWIW1mGFIXNkVx3+jAaOjz0x9RWl1IFYssxPewu6aQcJqrdkgDU1DaFaoCAMJQbNFRGaF"
    "UMkHERbsEGyIMh9aEETD2LK0KZZsMN2oBDsrCWbYqWwYEnD6QeHZ0RnHWWHb1w/jvb43Mybd"
    "ZXLgMW/u3Pvu7557zv+eeWz8O01xfRcAxfVdFNd38aq2Zy+3vlO/Zy+3vtUF0H4uxTFeY3ZV"
    "MQAaOwawqwrvdw5hVxVSesL2urGFsCMB7apioPYS8PcDEA6voWku+Xs4vGY0dgyIr28MNgcw"
    "GQkYFe6rTE3eNMNY4CpKy9E0FwG/i27vMMrpXuNNeTQHsKZ1kKnJm9y4com4owVHfJE7Mw9I"
    "pncl6OPQCiv3PuBR9Bq1xat84v+UHt/YG4EsMn+xq4oR8PfT4xsj7mhhY2GUtfA/uNg5SEVp"
    "OWc8TQD89tYfeRS9hl1ViDtauHHlEgF/v4zXNwKonO41Av5+bly5JH+saR2kpnUQu6rwOLQC"
    "QLd3GLuqyD4bC6PEHS2F5soFnB4fwl2n0nDyC1J6QnYQ93d/9xsACZeMBOQiIBOnAX8/jR0D"
    "BfVi0cGkhlM9DsDKtg+7qrCxMMrGwqgEajj5Bcn0rmWw6GNewPT4kIQvhB0DcjxmVxXpGWGP"
    "ote4wmFm17QOMj0+RNdHIwA0/+QDAJLpXWpaR4yl4IglYd5p7zPMoZHSEzx9ePu1SXXsh+9d"
    "NcySUlu8SpwWC6xoz24z24Xu3rwT2FXFaOwY4OnD20RiumyvKC3n/c4hA6CtrZnhnvN5YYtq"
    "i1dx16my4ZM/fGoBEd4V7R8PXJZ9m370PVJ6wrIDFaXlTI8PCY8ZAX8/0+NDVFeW4a5T5eVU"
    "j7MUHCHg7+fzz5clbA6gyMD9rahsFKfHgQfkdyHQjvgiKT1BY8cAtcWrTE3epKK0XI5Jpnfl"
    "OHedSrXtX3m9K6CXgiNMjw/lhbQpp3uNpeCIpdG8FdmWfaoI8OwE6vYO8/Th7SOfU11ZxubO"
    "HpBxTklVA5GYTo9vjKXgiO3tk1W0n0tZhdo8ofg0e0Z4UICKT3HKmNvNcVpdWZYzh4ADKKlq"
    "kDuY7cm8xcKvf3WOuKOFphN+VrZ9/OztEi5090oviWMQPgMg4HdxxtNEMr2LprkIh9dI6Qnp"
    "JTNMtgnvOes1Snb2cnYvrwdFXP71L/8F4G/P9qV3DuGQGtjtHbaM1zQXfw6OsrmzR3VlmZxU"
    "eNIMUVLVACD7Zhbcj3K615CAYsD+VpQL5w4nT6SPyQy9ceUSmuaScM/v35JaaVcVSwxWlJYj"
    "hH9s5jOCcyEiMZ31F2EiMZ3gXMgCLCyfp4vMFUhJVUPOuSpi6T/GkGzbWBhFKf1GelAsQMSr"
    "EO9ITJcFhhn+VUDCpscz8xVNTd6kxzeW00F4Z2NhlJSe4Mf1F4CMPv78F0XyMtvj0IoFIDgX"
    "4vd/eijvo3snSKZ36TzvkQsQZvamUIWVbZ8hZxCdzaIrzK4qRF+elvcr2z5Wtn08il6Tfe7M"
    "PJAZ/vz+LQCu/rLd8pyK0nKCcyHC4TW51ZGYTiSmS28KOLHQogMv2USgL8/2kdITPL9/C6X0"
    "G2paB0npCe7MPADAEV+UnjUXBUJqLnYenuFO9biEHO45L+NS01wyDoNzIQma7UEJKDyzrn9N"
    "SVUDtcWrNHYMkEhnVKi2eFUOEEeeqBVTekJCn/E08fHAZUtGijoynxaavRycC8k+Zl2VgPMT"
    "Xro+GiES07n3YBFHfBGP5z0c8UXuPVi0PDTg78cRz/S53P59CS108J32PjZ39tjfirIWy4TM"
    "+osw6/rXOYDCq5BJGrG9IrnMQm2bn/AaZ6+PEfD350C561TLNgiofCYy31mvAV8BGYVIHoxv"
    "KNsGwFWXWxWJhQrLFmrb/ISXHt+YDF4zVEPZNu461ZKpQgHElojfzMVH53kP+1tR+ZsQ57VY"
    "grtzSzmw5ufnPermJ7ycvZ6ZuK2tWcoCnIA93QLW1tZMj2+MtrZmNO1w9c56jc2dPTrPew7K"
    "OZVkTM/JbBECmuaSzjBnsW1m8SsuNv2ALyP/lINCoXcNj+cJANG9E3l1cn7Ci7NeY/1FGICz"
    "1yeBQ4F1qsfzViyAlBgzrFM9zt25JRl7FzsHsauKLa8HPZ4ntgMvGLwIMz/hZdOozanrBBxk"
    "9HNq8qY8RQDMZZyAM1syvWspljXNJXdAxHHeYsEEYAMIhd49qui0iWt5to/gXIil4IgUamFm"
    "iTHfm+FEhoutFc94JSCAs16zeTxPbKfcb0kY02UxEaubO3sWyOwz112nyr5mYFFbdnuHpXNe"
    "C/j/WvOHR1fP+eynp5zsb0XZNNWAmuaixzfG8mwfp9xvUVDA7Ar6VZVKdWUZ6y/ClrhMpnfp"
    "8Y0xP+G19C0YIGTix6x/2ToKmcTa3NmzZHRFaTnd3mFz+SbD57UvML+NZY6tBv7+5brlHY75"
    "X6K77hAMDvV0ebZPSJ0ltgsGOD0+JP+ViQmFCdHPZ1lbmpN4BQFs/vC2AZk4zI6hPBAAFpE/"
    "uM//ZqEQgHZVyYFz1mtHyhFYRN52FBwUyIMpPWFbnu0T/2XzTfad37wWMkneyDvq/wHQ9tx3"
    "Bcx8wwAAAABJRU5ErkJggg==")
gettipimg2Data = tipimg2.GetData
gettipimg2Image = tipimg2.GetImage
gettipimg2Bitmap = tipimg2.GetBitmap
gettipimg2Icon = tipimg2.GetIcon

